brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
namesrvAddr=rmqnamesrv:9876
brokerIP1=127.0.0.1
autoCreateTopicEnable=true
listenPort=10911