<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.shopee.banking</groupId>
        <artifactId>bams</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>bams-adapter</artifactId>
    <packaging>jar</packaging>
    <name>BAMS Adapter</name>

    <dependencies>
        <dependency>
            <groupId>com.shopee.banking</groupId>
            <artifactId>bams-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.shopee.banking</groupId>
            <artifactId>bams-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.shopee.banking</groupId>
            <artifactId>bams-app</artifactId>
        </dependency>
        <dependency>
            <groupId>com.shopee.banking</groupId>
            <artifactId>bams-infra</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aspectj</artifactId>
        </dependency>

        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <classifier>exec</classifier>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
